/**
 * Created by Beck Pang on 20171206
 *              system identification for gimbal yaw open loop system
 */

#include "ch.h"
#include "hal.h"
#include "gimbal.h"
#include "gimbal_simple_controller.h"
#include "system_identification.h"

static THD_WORKING_AREA(system_iden_wa, 2048);

/**
 * create excitement signal with N frequency, P period in each frequency
 * for the 2017/12/06, N = 30, and the excitation signal are generated by matlab
 */
volatile long long current_time_ms;
volatile float stop_time_table[31];
volatile float current_time;
volatile float test_time;
volatile double excitation;
static uint32_t clock_counter = 0;

static THD_FUNCTION(system_iden, ptr)
{
    (void)ptr;
    chRegSetThreadName("gimbal yaw system iden");

    int P = 5;
    int N = 30;
    float gain = 500.0f;
    int i, n;

    // Hardcoded sweeping frequency from 1Hz to 500Hz in log space
    float freq_log_space[30] = {1.0f,	1.23899037094209f,	1.53509713928722f,	1.90197057403762f,	    \
    2.35652322704781f,	2.91970958721362f,	3.61749206450498f,	4.48203783488109f,	5.55320171961581f,  \
    6.88036345850305f,	8.52470407366710f,	10.5620262624044f,	13.0862488367565f,	16.2137363004934f,  \
    20.0886631533056f,	24.8896602120448f,	30.8380493387440f,	38.2080461893409f,	47.3394013211040f,	\
    58.6530624030112f,	72.6705795435965f,	90.0381483052973f,	111.556398767719f,	138.217303890180f,	\
    171.249908617510f,	212.176987801808f,	262.885244821938f,	325.712286997135f,	403.554387286977f,	500.0f};

    // convert the frequency to build the stop time
    float stop_time_table[30] = {0};
    stop_time_table[0] = P * (1 / freq_log_space[0]);

    for (int i = 0; i < N; ++i) {
        stop_time_table[i] = stop_time_table[i-1] + P * (1 / freq_log_space[i]);
    }

    int wait_period = 5;
    chThdSleep(GIMBAL_CONTROL_PERIOD_NEXT * wait_period);

    long long int start_time_ms = (long long int) ST2MS(chVTGetSystemTimeX());

    uint32_t tick = chVTGetSystemTimeX();

    while (!chThdShouldTerminateX())
    {
        long long int current_time_ms_ns = ((long long int) ST2MS(chVTGetSystemTimeX()) - start_time_ms);
        if (current_time_ms > current_time_ms_ns) {
            clock_counter++;
        }
        current_time_ms = current_time_ms_ns;
        current_time =
                (current_time_ms + (clock_counter * (0xFFFFFFFF - CH_CFG_ST_FREQUENCY + 1UL) / CH_CFG_ST_FREQUENCY)) /
                1000.0f;
        if (n < N) {
            if (current_time > stop_time_table[n]) {
                n++;
            }
        }

        float period_time = current_time - stop_time_table[n - 1];
        float frequency = freq_log_space[n];
        test_time = (float) (2 * M_PI * frequency * period_time);
        excitation = gain * sinf((float) (2 * M_PI * frequency * period_time));
        gimbal.yaw_iq_output += excitation;

        tick += GIMBAL_CONTROL_PERIOD_NEXT;
        if (tick > chVTGetSystemTimeX()){
            chThdSleepUntil(tick);
        }
    }
}

void system_identification_init(void)
{
    chThdCreateStatic(system_iden_wa, sizeof(system_iden_wa),
                        NORMALPRIO - 6, system_iden, NULL);
}